/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/layout/AppFooter.vue')['default']
    BorderGlow: typeof import('./src/components/effects/BorderGlow.vue')['default']
    DownloadSection: typeof import('./src/components/sections/DownloadSection.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElectricBorder: typeof import('./src/components/effects/ElectricBorder.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTag: typeof import('element-plus/es')['ElTag']
    FAQSection: typeof import('./src/components/sections/FAQSection.vue')['default']
    FeaturesSection: typeof import('./src/components/sections/FeaturesSection.vue')['default']
    FloatingNavBar: typeof import('./src/components/layout/FloatingNavBar.vue')['default']
    GlassSurface: typeof import('./src/components/effects/GlassSurface.vue')['default']
    HeroSection: typeof import('./src/components/sections/HeroSection.vue')['default']
    NavBar: typeof import('./src/components/layout/NavBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SplashCursor: typeof import('./src/components/effects/SplashCursor.vue')['default']
  }
}
